/* opponents.js — who you get drawn against.
 *
 * NOT A LADDER, AND NOT A ROSTER EITHER ANY MORE
 * The old build fought whatever you had parked in hangar slot 2. The first
 * rebuild made it a ladder — nine rungs, beat one to open the next — which is
 * gone because it forces every challenge to name a name ("beat the
 * Inquisitor") and Dan's rule is that no operation may name an opponent. The
 * second was a baked pool of five fits per tier, in `data/opponents.json`.
 *
 * NOW THE OPPONENT IS BUILT WHEN YOU PRESS ENTER ARENA. A hull is drawn from
 * your tier and `Autofit` packs it, with the AUTOFIT menu's own options rolled
 * at random — including the `placement` mode the menu never shows, because a
 * clumsily placed fit is the only honest way to make an easy opponent when
 * difficulty is PURELY the fit. That gives every fight a fresh ship instead of
 * one of five, and it means improving the packer improves the whole game.
 *
 * `data/opponents.json` is still loaded and still generated by
 * `tools/make-opponents.js`, because `editor.html` tunes those rows by hand and
 * `tools/balance.js` fights them against each other. The GAME no longer draws
 * from it — `draw()` generates.
 */
var Opponents = (function () {
  var list = [];

  /* A name, so two fits of the same hull are not the same contact. Seeded off
     the recipe, so a given hull-and-recipe always reads the same. */
  var CALLSIGN = ['Vesper', 'Harrow', 'Kestrel', 'Tallow', 'Cinder', 'Rook',
                  'Marrow', 'Quill', 'Ember', 'Sable', 'Wrack', 'Thorn',
                  'Gallows', 'Pale', 'Verge', 'Hollow'];

  function mulberry32(a) {
    return function () {
      a |= 0; a = a + 0x6D2B79F5 | 0;
      var t = Math.imul(a ^ a >>> 15, 1 | a);
      t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
      return ((t ^ t >>> 14) >>> 0) / 4294967296;
    };
  }
  function pick(arr, rng) { return arr[(rng() * arr.length) | 0]; }
  function hash(str) {
    var h = 2166136261;
    for (var i = 0; i < str.length; i++) { h ^= str.charCodeAt(i); h = Math.imul(h, 16777619); }
    return h >>> 0;
  }

  /* Build one. Returns a row shaped exactly like a `opponents.json` row, so
     everything downstream — the arena HUD, the result screen, the save — cannot
     tell the difference. */
  function generate(tier, seed) {
    var t = Progress.tier(tier);
    var ships = (t && t.ships) || [];
    if (!ships.length) return null;
    var rng = mulberry32(seed === undefined ? (Math.random() * 1e9) | 0 : seed);

    for (var attempt = 0; attempt < 8; attempt++) {
      var ship = ships[(rng() * ships.length) | 0];
      /* The fit is built with what a pilot flying THIS hull would have
         unlocked, not with everything in the game — otherwise a tier 1 skiff
         turns up carrying a Fusion Turret. */
      var lvl = ship.lr || 1;
      var recipe = {
        weapons:   pick(Autofit.WEAPON_MODES, rng),
        armour:    pick(Autofit.ARMOUR_MODES, rng),
        priority:  pick(Autofit.PRIORITY_MODES, rng),
        placement: pick(Autofit.PLACEMENT_MODES, rng)
      };
      var modules = Autofit.build(ship, {
        weapons: recipe.weapons, armour: recipe.armour, priority: recipe.priority,
        placement: recipe.placement, seed: (rng() * 1e9) | 0,
        allow: function (m) { return Progress.levelOfModule(m.key) <= lvl; }
      }, Data.modules);

      if (!Geom.validate(ship, modules, Data.modules).ok) continue;

      var tag = ship.key + ':' + recipe.weapons + '/' + recipe.armour + '/' +
                recipe.priority + '/' + recipe.placement;
      var call = CALLSIGN[hash(tag) % CALLSIGN.length];
      return {
        /* The id is the HULL, not the recipe. It is what `beaten` is keyed on,
           and a save that grew an entry per recipe would grow without bound. */
        id: 'gen:' + ship.key,
        name: ship.displayName + ' ' + call,
        callsign: call,
        blurb: recipe.weapons + ' · ' + recipe.armour + ' · ' + recipe.priority,
        difficulty: tier,
        tier: tier,
        generated: recipe,
        ship: { shipId: ship.key, modules: modules }
      };
    }
    return null;
  }

  function load(cb, fail) {
    fetch('./data/opponents.json')
      .then(function (r) { if (!r.ok) throw new Error('opponents.json ' + r.status); return r.json(); })
      .then(function (j) { list = j.opponents || []; cb(list); })
      .catch(function (e) { (fail || function () {})(e); });
  }

  function pool(tier) {
    var out = list.filter(function (o) { return o.tier === tier; });
    /* Never hand back nothing: a tier with no fits would dead-end the game, so
       fall back to the nearest tier that has any. */
    if (out.length) return out;
    var best = null, dist = 1e9;
    for (var i = 0; i < list.length; i++) {
      var d = Math.abs(list[i].tier - tier);
      if (d < dist) { dist = d; best = list[i].tier; }
    }
    return best === null ? [] : list.filter(function (o) { return o.tier === best; });
  }

  /* Draw a fight: build a fresh one. Falls back to the baked roster only if
     generation cannot produce a flyable fit for this tier, which would mean
     the packer is broken — `tools/autofit-test.js` exists to stop that. */
  function draw(tier) {
    var made = generate(tier);
    if (made) return made;
    var p = pool(tier);
    if (!p.length) return null;
    return p[(Math.random() * p.length) | 0];
  }

  function beaten(id) { return Save.get().beaten.indexOf(id) >= 0; }

  return {
    load: load,
    generate: generate,
    get list() { return list; },
    pool: pool,
    draw: draw,
    byId: function (id) {
      for (var i = 0; i < list.length; i++) if (list[i].id === id) return list[i];
      return null;
    },
    beaten: beaten,
    record: function (id) { var r = Save.get().results[id]; return r || { wins: 0, losses: 0 }; },
    /* How much of one tier's pool has been beaten — the hangar's one-line status. */
    tierProgress: function (tier) {
      var p = pool(tier), n = 0;
      for (var i = 0; i < p.length; i++) if (beaten(p[i].id)) n++;
      return { beaten: n, total: p.length };
    },
    /* The fit the sim wants, straight out of the roster row. */
    fitFor: function (o) {
      return { shipId: o.ship.shipId, modules: o.ship.modules };
    }
  };
})();
