/* progress.js — levels, operations, and what is unlocked.
 *
 * Difficulty is the ship fit and nothing else (see js/sim/ai.js), so the game's
 * only other axis is WHAT YOU ARE ALLOWED TO BOLT ON. That is this file.
 *
 * OPERATIONS are challenges. Completing any one that is currently available
 * gives you a level, and a level hands over a hull and a couple of modules.
 * Two new operations become visible per level and old ones stay, so there are
 * always three or four to pick from and the late ones are not even hinted at.
 * Four operations are TIER GATES: the only way into the next tier, each asking
 * you to beat an opponent from the tier above while flying a hull from the tier
 * you are finishing.
 *
 * No operation names an opponent. Fights come from a generated pool for your
 * tier, so a condition may ask about an opponent's TIER and never its identity.
 * Hulls are different — those are fixed data the player earns.
 *
 * The tree lives in data/progression.json, generated by
 * tools/make-progression.js from tools/operations.json. Edit those, re-run the
 * generator, and both the game and docs/game-fleet-forge-progression.md move
 * together. Do not hand-edit the json.
 */
var Progress = (function () {
  var P = null;            /* data/progression.json */
  var tiers = null;        /* tier -> {..., ships: [shipData]} */

  function load(cb, fail) {
    fetch('./data/progression.json')
      .then(function (r) { if (!r.ok) throw new Error('progression.json ' + r.status); return r.json(); })
      .then(function (j) { P = j; cb(j); })
      .catch(function (e) { (fail || function () {})(e); });
  }

  /* ---- tiers ---------------------------------------------------------- */
  function buildTiers() {
    if (tiers) return tiers;
    tiers = P.tiers.map(function (t) {
      var ships = Data.shipList.filter(function (s) {
        return (s.lr || 0) >= t.lr[0] && (s.lr || 0) <= t.lr[1];
      }).sort(function (a, b) {
        return (P.shipLevel[a.key] || 99) - (P.shipLevel[b.key] || 99) ||
               a.displayName.localeCompare(b.displayName);
      });
      return { n: t.n, label: t.name, blurb: '', lr: t.lr,
               fromLevel: t.fromLevel, toLevel: t.toLevel, ships: ships };
    });
    /* The blurb is the level band, because that is the only thing about a tier
       the player can act on. The tier's NAME is Space Arena's own ship class. */
    tiers.forEach(function (t) { t.blurb = 'lv ' + t.fromLevel + '–' + t.toLevel; });
    return tiers;
  }

  function tierOfLr(lr) {
    for (var i = 0; i < P.tiers.length; i++)
      if (lr >= P.tiers[i].lr[0] && lr <= P.tiers[i].lr[1]) return P.tiers[i].n;
    return P.tiers.length;
  }

  /* ---- the player's progression state, held in the save ---------------- */
  function st() { return Save.progress(); }

  function level() { return st().level; }

  /* ---- conditions ------------------------------------------------------
     `ev` is a battle or fit event, or null when only the running counters are
     being re-checked. A condition returns true the moment it is satisfied. */
  var COND = {
    /* running counters */
    wins:          function (c, ev, s) { return s.wins >= c.n; },
    streak:        function (c, ev, s) { return s.bestStreak >= c.n; },
    winsAtOwnTier: function (c, ev, s) { return s.winsAtOwnTier >= c.n; },
    streakAtTier:  function (c, ev, s) { return (s.bestStreakAtTier[c.oppTier] || 0) >= c.n; },
    hullWins:      function (c, ev, s) { return (s.hullWins[c.ship] || 0) >= c.n; },
    twoHulls:      function (c, ev, s) {
      for (var k in s.tierHulls) if (s.tierHulls[k].length >= 2) return true;
      return false;
    },
    layouts:       function (c, ev, s) { return s.maxLayouts >= c.n; },
    fillCells:     function (c, ev, s) { return s.maxFilled >= (c.min || 1); },
    ownTier:       function (c, ev, s) {
      var ts = buildTiers();
      for (var i = 0; i < ts.length; i++) {
        var all = ts[i].ships.length > 0;
        for (var j = 0; j < ts[i].ships.length; j++)
          if (!Save.owned(ts[i].ships[j].key)) { all = false; break; }
        if (all) return true;
      }
      return false;
    },

    /* single-battle predicates — all require a win */
    health:      function (c, ev) { return win(ev, c) && ev.health >= c.min; },
    time:        function (c, ev) { return win(ev, c) && ev.time <= c.max; },
    reason:      function (c, ev) { return win(ev, c) && ev.reason === c.v; },
    noLoss:      function (c, ev) { return win(ev, c) && ev.modulesLost === 0; },
    cells:       function (c, ev) {
      return win(ev, c) &&
        (c.max === undefined || ev.cells <= c.max) &&
        (c.min === undefined || ev.cells >= c.min);
    },
    newHull:     function (c, ev, s) {
      return win(ev, c) && !s.wonHulls[ev.shipId];
    },
    fullWin:     function (c, ev) { return win(ev, c) && ev.cellsUsed >= ev.cells; },
    minWeapons:  function (c, ev) { return win(ev, c) && ev.weapons >= c.n; },
    minReactors: function (c, ev) { return win(ev, c) && ev.reactors >= c.n; },
    minTurrets:  function (c, ev) { return win(ev, c) && ev.turrets >= c.n; },
    has:         function (c, ev) { return win(ev, c) && ev.subs[c.sub] > 0; },
    without:     function (c, ev) { return win(ev, c) && !ev.subs[c.sub]; },
    hasAll:      function (c, ev) {
      if (!win(ev, c)) return false;
      for (var i = 0; i < c.subs.length; i++) if (!ev.subs[c.subs[i]]) return false;
      return true;
    },
    hasModule:   function (c, ev) { return win(ev, c) && !!ev.mods[c.m]; },
    allTypes:    function (c, ev) {
      return win(ev, c) && ev.types.ballistic && ev.types.laser && ev.types.missile;
    },
    only:        function (c, ev) {
      if (!win(ev, c)) return false;
      var t = ev.types, n = 0, k;
      for (k in t) if (t[k]) n++;
      return n === 1 && !!t[c.dt];
    },
    step:        function (c, ev) {
      return win(ev, null) && ev.hullTier === c.hull && ev.oppTier === c.opp;
    }
  };

  /* Shared gate on every battle predicate: it must be a win, and any oppTier /
     hullTier qualifier on the condition must match. */
  function win(ev, c) {
    if (!ev || ev.kind !== 'battle' || !ev.won) return false;
    if (c && c.oppTier !== undefined && ev.oppTier !== c.oppTier) return false;
    if (c && c.hullTier !== undefined && ev.hullTier !== c.hullTier) return false;
    return true;
  }

  function opById(id) {
    for (var i = 0; i < P.operations.length; i++)
      if (P.operations[i].id === id) return P.operations[i];
    return null;
  }

  /* Visible now: revealed at or below the current level, and not yet done.
     A tier gate is hidden until the player is actually at the last level of
     the tier it closes — it is the wall, not one of the choices. */
  function available() {
    var s = st(), lv = s.level, out = [];
    for (var i = 0; i < P.operations.length; i++) {
      var o = P.operations[i];
      if (s.ops[o.id]) continue;
      if (o.at > lv) continue;
      out.push(o);
    }
    return out;
  }

  /* The gate that must be passed to leave the level the player is on, or null
     when this level is an ordinary one. */
  function gateAt(lv) {
    for (var i = 0; i < P.operations.length; i++)
      if (P.operations[i].gate && P.operations[i].at === lv) return P.operations[i];
    return null;
  }

  /* Run every available operation against an event. Each that completes grants
     one level. A level that is gated only advances on its own gate operation. */
  var evaluating = false;     /* Save.unlockShip calls back in here */

  function evaluate(ev) {
    if (evaluating) return [];
    evaluating = true;
    try { return evaluateInner(ev); } finally { evaluating = false; }
  }

  function evaluateInner(ev) {
    var s = st(), granted = [], list = available(), i;
    for (i = 0; i < list.length; i++) {
      var o = list[i], fn = COND[o.cond.t];
      if (!fn) continue;                       /* unknown condition: never fires */
      if (!fn(o.cond, ev, s)) continue;
      s.ops[o.id] = 1;
      granted.push(o);
    }
    /* Award levels for what completed, respecting the gate on the current level. */
    var gained = [];
    for (i = 0; i < granted.length; i++) {
      var g = gateAt(s.level);
      if (g && granted[i].id !== g.id) continue;      /* the wall holds */
      if (s.level >= P.maxLevel) break;
      s.level += 1;
      var u = unlocksAt(s.level);
      /* A level hands the hull over — the player should not have to go and
         claim it. Modules need no equivalent: moduleUnlocked reads the level. */
      for (var j = 0; j < u.ships.length; j++) Save.unlockShip(u.ships[j]);
      gained.push({ op: granted[i], level: s.level, unlocks: u });
    }
    if (granted.length) Save.saveProgress();
    return gained;
  }

  function unlocksAt(lv) {
    for (var i = 0; i < P.levels.length; i++)
      if (P.levels[i].level === lv) {
        return { ships: P.levels[i].ships.slice(), modules: P.levels[i].modules.slice() };
      }
    return { ships: [], modules: [] };
  }

  /* ---- how far along one operation is ---------------------------------
     The hangar draws "4/5" and a bar against every visible op, so each
     condition needs a count as well as a yes/no. The counter-based ones read
     straight out of the save; a single-battle predicate genuinely has no
     partial state — you either win that fight or you do not — so it reports
     0/1, which is what the design draws for an op not yet started. */
  var PROG = {
    wins:          function (c, s) { return [s.wins, c.n]; },
    streak:        function (c, s) { return [s.bestStreak, c.n]; },
    winsAtOwnTier: function (c, s) { return [s.winsAtOwnTier, c.n]; },
    streakAtTier:  function (c, s) { return [s.bestStreakAtTier[c.oppTier] || 0, c.n]; },
    hullWins:      function (c, s) { return [s.hullWins[c.ship] || 0, c.n]; },
    layouts:       function (c, s) { return [s.maxLayouts, c.n]; },
    fillCells:     function (c, s) { return [s.maxFilled > 0 ? 1 : 0, 1]; },
    twoHulls:      function (c, s) {
      var best = 0;
      for (var k in s.tierHulls) best = Math.max(best, s.tierHulls[k].length);
      return [Math.min(best, 2), 2];
    }
  };

  function opProgress(op) {
    var s = st();
    if (st().ops[op.id]) {
      var f = PROG[op.cond.t];
      var n = f ? f(op.cond, s)[1] : 1;
      return { have: n, need: n, done: true };
    }
    var fn = PROG[op.cond.t];
    if (!fn) return { have: 0, need: 1, done: false };
    var r = fn(op.cond, s);
    return { have: Math.min(r[0], r[1]), need: r[1], done: false };
  }

  /* ---- what is waiting up the tree ------------------------------------
     The UNLOCKS half of the hangar's right column. Levels above the current
     one, in order, flattened to one row per thing earned. The generated
     `levels` array can carry the same level twice (the hard-coded level 1 and
     the allocated one), so rows are deduplicated by what they unlock and not
     by the level they sit on. */
  function upcoming(limit) {
    var lv = level(), out = [], seen = {};
    for (var i = 0; i < P.levels.length && out.length < (limit || 8); i++) {
      var L = P.levels[i];
      if (L.level <= lv) continue;
      var j;
      for (j = 0; j < L.ships.length; j++) push(L.level, L.ships[j], 'ship');
      for (j = 0; j < L.modules.length; j++) push(L.level, L.modules[j], 'module');
    }
    function push(level, key, kind) {
      if (seen[kind + key] || out.length >= (limit || 8)) return;
      seen[kind + key] = 1;
      if (kind === 'ship') {
        var sh = Data.ship(key);
        if (!sh) return;
        out.push({ level: level, kind: 'ship', label: sh.displayName + ' · T' + tierOfLr(sh.lr || 0),
                   family: 'ship' });
      } else {
        var m = Data.module(key);
        if (!m) return;
        out.push({ level: level, kind: 'module', label: m.displayName,
                   family: T.familyOf(m) });
      }
    }
    out.sort(function (a, b) { return a.level - b.level; });
    return out;
  }

  return {
    MAX_LAYOUTS: 3,
    load: load,
    get data() { return P; },
    get tiers() { return buildTiers(); },
    tier: function (n) { return buildTiers()[n - 1]; },
    tierOf: function (ship) { return tierOfLr((ship && ship.lr) || 0); },
    level: level,
    maxLevel: function () { return P.maxLevel; },

    /* ---- the gates ----------------------------------------------------- */
    shipUnlocked:   function (s) { return !!s && (P.shipLevel[s.key]   || 99) <= level(); },
    moduleUnlocked: function (m) { return !!m && (P.moduleLevel[m.key] || 99) <= level(); },
    tierUnlocked:   function (n) {
      var t = buildTiers()[n - 1];
      return !!t && level() >= t.fromLevel;
    },

    /* ---- operations ---------------------------------------------------- */
    available: available,
    opProgress: opProgress,
    upcoming: upcoming,
    gateAt: gateAt,
    currentGate: function () { return gateAt(level()); },
    done: function (id) { return !!st().ops[id]; },
    all: function () { return P.operations; },
    unlocksAt: unlocksAt,
    levelOfShip:  function (k) { return P.shipLevel[k] || 99; },
    levelOfModule: function (k) { return P.moduleLevel[k] || 99; },

    /* ---- events -------------------------------------------------------- */
    recordBattle: function (ev) { Save.applyBattle(ev); return evaluate(ev); },
    recordFit:    function (ev) { Save.applyFit(ev); return evaluate(ev); },
    /* re-check the counter-only conditions, e.g. after a ship is acquired */
    recheck:      function ()   { return evaluate(null); },

    tierProgress: function (n) {
      var t = buildTiers()[n - 1], have = 0;
      if (!t) return { have: 0, total: 0 };
      for (var i = 0; i < t.ships.length; i++) if (Save.owned(t.ships[i].key)) have++;
      return { have: have, total: t.ships.length };
    }
  };
})();
