/* art.js — GENERATED by build/artmanifest.py. Do not edit by hand.
 *
 * The pictures, and only the pictures that actually exist. Everything that
 * draws something asks here first and falls back to the generated SVG plate
 * when the answer is null, so the game runs with all of the art, some of it,
 * or none of it.
 *
 *   Art.plant(id)        the coloured specimen, for the desk, shelf and counter
 *   Art.book(id)         the line-drawn plate, for the book page
 *   Art.person(who)      a customer's face
 *   Art.place(hid, day)  a location, in the state the story has left it in
 *   Art.story(key)       "prologue_0", "evening_07", "ending_end_keep"
 *   Art.asset(id)        a piece of furniture
 *   Art.note(paperId)    the painted sheet that one note is written on
 *   Art.img(url, opts)   an <img> for any of the above
 *   Art.css(url)         the same as a CSS url(), or "none"
 */

const Art = (function () {

  /* Where the pictures are served from. By default the art/ folder sitting next
     to this page, which is what you want locally and what you want on a host
     that serves the whole folder. To put the art somewhere else — a CDN, a
     different Netlify site — set window.DRAGONSEED_ART_BASE (with a trailing
     slash) before this file loads; index.html has the line, commented out.

     Nine background-image rules in css/style.css point at ../art/ directly and
     this does not reach them. Grep for `url("../art/` if the art ever moves. */
  var BASE = (typeof window !== "undefined" && window.DRAGONSEED_ART_BASE) || "art/";

  var PLANT  = {
 "n007": "plant_n007_embercup.webp",
 "n019": "plant_n019_moonlace.webp",
 "n044": "plant_n044_suncoin.webp",
 "n052": "plant_n052_fenwhistle.webp",
 "n088": "plant_n088_scarwort.webp",
 "n094": "plant_n094_duskmoth.webp",
 "n099": "plant_n099_gravewreath.webp",
 "n115": "plant_n115_thorncrown.webp",
 "n128": "plant_n128_gloambell.webp",
 "n130": "plant_n130_fellgorse.webp",
 "n150": "plant_n150_wintervane.webp",
 "n162": "plant_n162_pinkhaven.webp",
 "n163": "plant_n163_kittleberry.webp",
 "n176": "plant_n176_lanternhead.webp",
 "n201": "plant_n201_skyreed.webp",
 "n210": "plant_n210_tarnlace.webp",
 "n219": "plant_n219_bluecoin.webp",
 "n233": "plant_n233_harrowbell.webp",
 "n244": "plant_n244_cauldwick.webp",
 "n255": "plant_n255_winterglass.webp",
 "n262": "plant_n262_deepwhistle.webp",
 "n271": "plant_n271_larkspire.webp",
 "n287": "plant_n287_butterdale.webp",
 "n293": "plant_n293_meakdew.webp",
 "n301": "plant_n301_verecund.webp",
 "n308": "plant_n308_pryttle.webp",
 "n314": "plant_n314_nightvane.webp",
 "n320": "plant_n320_bellanox.webp",
 "n327": "plant_n327_norwood.webp",
 "n334": "plant_n334_saint-quill.webp",
 "n341": "plant_n341_feverkiss.webp",
 "n348": "plant_n348_candlewood.webp",
 "n355": "plant_n355_widow-s-woe.webp",
 "n362": "plant_n362_weeping-belle.webp",
 "n369": "plant_n369_storian.webp",
 "n376": "plant_n376_maiden-s-sorrow.webp",
 "n383": "plant_n383_royal-gentia.webp",
 "n390": "plant_n390_trimblehuff.webp",
 "n397": "plant_n397_ambrella.webp",
 "n404": "plant_n404_longmeg.webp",
 "n411": "plant_n411_witchphygg.webp",
 "n418": "plant_n418_forest-camphry.webp",
 "n425": "plant_n425_lesser-merrydock.webp",
 "n432": "plant_n432_phennet.webp",
 "n439": "plant_n439_goldenlight.webp",
 "n446": "plant_n446_gandyroot.webp",
 "n453": "plant_n453_mary-s-breath.webp",
 "n460": "plant_n460_worryless.webp",
 "n467": "plant_n467_palliance.webp",
 "n474": "plant_n474_elderphinium.webp",
 "n481": "plant_n481_frostcup.webp",
 "n488": "plant_n488_sheepsnap.webp",
 "n495": "plant_n495_swiftsnare.webp",
 "n502": "plant_n502_common-trouse.webp",
 "n509": "plant_n509_brimlock.webp",
 "n516": "plant_n516_eyebright.webp",
 "n523": "plant_n523_hopheart.webp",
 "n530": "plant_n530_mellowglow.webp",
 "n537": "plant_n537_jacob-s-worth.webp",
 "n544": "plant_n544_shimmerlung.webp",
 "n551": "plant_n551_henchuck.webp",
 "n558": "plant_n558_larkshine.webp",
 "n565": "plant_n565_emberfell.webp",
 "n572": "plant_n572_sour-bandy.webp",
 "n579": "plant_n579_lemon-dandy.webp",
 "n586": "plant_n586_ghostcap.webp",
 "n593": "plant_n593_wanderlamp.webp",
 "n600": "plant_n600_bishop-s-parasol.webp",
 "n607": "plant_n607_copper-caledonian.webp",
 "n614": "plant_n614_farmer-s-worry.webp",
 "n621": "plant_n621_fool-s-midnight.webp",
 "n628": "plant_n628_dead-man-s-fingers.webp",
 "n635": "plant_n635_liverstone.webp",
 "n642": "plant_n642_spring-waxcap.webp",
 "n649": "plant_n649_sunset-mountcap.webp",
 "n656": "plant_n656_glowhorn.webp",
 "n663": "plant_n663_grey-sandfire.webp",
 "n670": "plant_n670_gilded-dendra.webp",
 "n677": "plant_n677_devil-s-nightcap.webp",
 "n684": "plant_n684_solomon-s-sceptre.webp",
 "n691": "plant_n691_twilight-lepiota.webp",
 "n698": "plant_n698_blackfen-ren.webp"
};
  var BOOK   = {
 "n007": "plantbook_n007_embercup.webp",
 "n019": "plantbook_n019_moonlace.webp",
 "n044": "plantbook_n044_suncoin.webp",
 "n052": "plantbook_n052_fenwhistle.webp",
 "n088": "plantbook_n088_scarwort.webp",
 "n094": "plantbook_n094_duskmoth.webp",
 "n099": "plantbook_n099_gravewreath.webp",
 "n115": "plantbook_n115_thorncrown.webp",
 "n128": "plantbook_n128_gloambell.webp",
 "n130": "plantbook_n130_fellgorse.webp",
 "n150": "plantbook_n150_wintervane.webp",
 "n162": "plantbook_n162_pinkhaven.webp",
 "n163": "plantbook_n163_kittleberry.webp",
 "n176": "plantbook_n176_lanternhead.webp",
 "n201": "plantbook_n201_skyreed.webp",
 "n210": "plantbook_n210_tarnlace.webp",
 "n219": "plantbook_n219_bluecoin.webp",
 "n233": "plantbook_n233_harrowbell.webp",
 "n244": "plantbook_n244_cauldwick.webp",
 "n255": "plantbook_n255_winterglass.webp",
 "n262": "plantbook_n262_deepwhistle.webp",
 "n271": "plantbook_n271_larkspire.webp",
 "n287": "plantbook_n287_butterdale.webp",
 "n293": "plantbook_n293_meakdew.webp",
 "n301": "plantbook_n301_verecund.webp",
 "n308": "plantbook_n308_pryttle.webp",
 "n314": "plantbook_n314_nightvane.webp",
 "n320": "plantbook_n320_bellanox.webp",
 "n327": "plantbook_n327_norwood.webp",
 "n334": "plantbook_n334_saint-quill.webp",
 "n341": "plantbook_n341_feverkiss.webp",
 "n348": "plantbook_n348_candlewood.webp",
 "n355": "plantbook_n355_widow-s-woe.webp",
 "n362": "plantbook_n362_weeping-belle.webp",
 "n369": "plantbook_n369_storian.webp",
 "n376": "plantbook_n376_maiden-s-sorrow.webp",
 "n383": "plantbook_n383_royal-gentia.webp",
 "n390": "plantbook_n390_trimblehuff.webp",
 "n397": "plantbook_n397_ambrella.webp",
 "n404": "plantbook_n404_longmeg.webp",
 "n411": "plantbook_n411_witchphygg.webp",
 "n418": "plantbook_n418_forest-camphry.webp",
 "n425": "plantbook_n425_lesser-merrydock.webp",
 "n432": "plantbook_n432_phennet.webp",
 "n439": "plantbook_n439_goldenlight.webp",
 "n446": "plantbook_n446_gandyroot.webp",
 "n453": "plantbook_n453_mary-s-breath.webp",
 "n460": "plantbook_n460_worryless.webp",
 "n467": "plantbook_n467_palliance.webp",
 "n474": "plantbook_n474_elderphinium.webp",
 "n481": "plantbook_n481_frostcup.webp",
 "n488": "plantbook_n488_sheepsnap.webp",
 "n495": "plantbook_n495_swiftsnare.webp",
 "n502": "plantbook_n502_common-trouse.webp",
 "n509": "plantbook_n509_brimlock.webp",
 "n516": "plantbook_n516_eyebright.webp",
 "n523": "plantbook_n523_hopheart.webp",
 "n530": "plantbook_n530_mellowglow.webp",
 "n537": "plantbook_n537_jacob-s-worth.webp",
 "n544": "plantbook_n544_shimmerlung.webp",
 "n551": "plantbook_n551_henchuck.webp",
 "n558": "plantbook_n558_larkshine.webp",
 "n565": "plantbook_n565_emberfell.webp",
 "n572": "plantbook_n572_sour-bandy.webp",
 "n579": "plantbook_n579_lemon-dandy.webp",
 "n586": "plantbook_n586_ghostcap.webp",
 "n593": "plantbook_n593_wanderlamp.webp",
 "n600": "plantbook_n600_bishop-s-parasol.webp",
 "n607": "plantbook_n607_copper-caledonian.webp",
 "n614": "plantbook_n614_farmer-s-worry.webp",
 "n621": "plantbook_n621_fool-s-midnight.webp",
 "n628": "plantbook_n628_dead-man-s-fingers.webp",
 "n635": "plantbook_n635_liverstone.webp",
 "n642": "plantbook_n642_spring-waxcap.webp",
 "n649": "plantbook_n649_sunset-mountcap.webp",
 "n656": "plantbook_n656_glowhorn.webp",
 "n663": "plantbook_n663_grey-sandfire.webp",
 "n670": "plantbook_n670_gilded-dendra.webp",
 "n677": "plantbook_n677_devil-s-nightcap.webp",
 "n684": "plantbook_n684_solomon-s-sceptre.webp",
 "n691": "plantbook_n691_twilight-lepiota.webp",
 "n698": "plantbook_n698_blackfen-ren.webp"
};
  var PERSON = {
 "baby": "person_baby.webp",
 "coyle": "person_coyle.webp",
 "dragon": "person_dragon.webp",
 "ivo": "person_ivo.webp",
 "nan": "person_nan.webp",
 "tom": "person_tom.webp",
 "warden": "person_warden.webp",
 "wren": "person_wren.webp"
};
  var LOC    = {
 "barrow_closed": "loc_barrow_closed.webp",
 "barrow_opened": "loc_barrow_opened.webp",
 "bed": "loc_bed.webp",
 "cave": "loc_cave.webp",
 "cellar": "loc_cellar.webp",
 "coast": "loc_coast.webp",
 "crag": "loc_crag.webp",
 "fen": "loc_fen.webp",
 "garden": "loc_garden.webp",
 "gorge": "loc_gorge.webp",
 "meadow": "loc_meadow.webp",
 "moor_after": "loc_moor_after.webp",
 "moor_before": "loc_moor_before.webp",
 "pike_broken": "loc_pike_broken.webp",
 "pike_whole": "loc_pike_whole.webp",
 "river": "loc_river.webp",
 "scar": "loc_scar.webp",
 "shop": "loc_shop.webp",
 "tarn_drained": "loc_tarn_drained.webp",
 "tarn_full": "loc_tarn_full.webp",
 "town": "loc_town.webp",
 "valley": "loc_valley.webp",
 "wood": "loc_wood.webp",
 "yard": "loc_yard.webp"
};
  var STORY  = {
 "ending_end_keep": "story_ending_end_keep.webp",
 "ending_end_return": "story_ending_end_return.webp",
 "ending_none": "story_ending_none.webp",
 "evening_01": "story_evening_01.webp",
 "evening_02": "story_evening_02.webp",
 "evening_03": "story_evening_03.webp",
 "evening_04": "story_evening_04.webp",
 "evening_05": "story_evening_05.webp",
 "evening_06": "story_evening_06.webp",
 "evening_07": "story_evening_07.webp",
 "evening_08": "story_evening_08.webp",
 "evening_09": "story_evening_09.webp",
 "evening_10": "story_evening_10.webp",
 "evening_11": "story_evening_11.webp",
 "evening_12": "story_evening_12.webp",
 "evening_13": "story_evening_13.webp",
 "evening_14": "story_evening_14.webp",
 "evening_15": "story_evening_15.webp",
 "evening_16": "story_evening_16.webp",
 "prologue_0": "story_prologue_0.webp",
 "prologue_1": "story_prologue_1.webp",
 "prologue_2": "story_prologue_2.webp"
};
  var ASSET  = {
 "bell": "asset_bell.webp",
 "book_closed": "asset_book_closed.webp",
 "book_open": "asset_book_open.webp",
 "dayend_card": "asset_dayend_card.webp",
 "desk_mat": "asset_desk_mat.webp",
 "desk_surface": "asset_desk_surface.webp",
 "drawer_front": "asset_drawer_front.webp",
 "drawer_open": "asset_drawer_open.webp",
 "egg_in_sand": "asset_egg_in_sand.webp",
 "label_stamp": "asset_label_stamp.webp",
 "lamp": "asset_lamp.webp",
 "lens": "asset_lens.webp",
 "map_paper": "asset_map_paper.webp",
 "paper_sheet": "asset_paper_sheet.webp",
 "pot_cutting": "asset_pot_cutting.webp",
 "pot_empty": "asset_pot_empty.webp",
 "rune_stones": "asset_rune_stones.webp",
 "shelf_tall": "asset_shelf_tall.webp",
 "shelf_wall": "asset_shelf_wall.webp",
 "shelf_wide": "asset_shelf_wide.webp",
 "start_backdrop": "asset_start_backdrop.webp",
 "window_rain": "asset_window_rain.webp"
};
  var NOTE   = {
 "p_alice1": "asset_note_p_alice1.webp",
 "p_alice2": "asset_note_p_alice2.webp",
 "p_barrowmap": "asset_note_p_barrowmap.webp",
 "p_bill": "asset_note_p_bill.webp",
 "p_bramwell": "asset_note_p_bramwell.webp",
 "p_gorge": "asset_note_p_gorge.webp",
 "p_hester1": "asset_note_p_hester1.webp",
 "p_hester2": "asset_note_p_hester2.webp",
 "p_hester3": "asset_note_p_hester3.webp",
 "p_hester4": "asset_note_p_hester4.webp",
 "p_inventory": "asset_note_p_inventory.webp",
 "p_muster": "asset_note_p_muster.webp",
 "p_sketch1": "asset_note_p_sketch1.webp",
 "p_wanted": "asset_note_p_wanted.webp"
};

  /* Four places the mother changes on her way through. Each entry is the last
     day that phase is what you would see. */
  var PHASES = {
 "barrow": [
  [
   10,
   "closed"
  ],
  [
   99,
   "opened"
  ]
 ],
 "moor": [
  [
   5,
   "before"
  ],
  [
   99,
   "after"
  ]
 ],
 "pike": [
  [
   14,
   "whole"
  ],
  [
   99,
   "broken"
  ]
 ],
 "tarn": [
  [
   7,
   "full"
  ],
  [
   99,
   "drained"
  ]
 ]
};

  function url(f) { return f ? BASE + f : null; }

  function place(hid, day) {
    var ph = PHASES[hid];
    if (ph) {
      for (var i = 0; i < ph.length; i++)
        if (day <= ph[i][0] || i === ph.length - 1) {
          var u = url(LOC[hid + "_" + ph[i][1]]);
          if (u) return u;
          break;
        }
    }
    return url(LOC[hid]);
  }

  function esc(s) { return String(s).replace(/[&<>"]/g, function (c) {
    return { "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;" }[c]; }); }

  /* Always object-fit: contain, because the art is square or 4:3 and the boxes
     it goes in are neither. Never let a plate be squashed. */
  function img(u, o) {
    if (!u) return "";
    o = o || {};
    return '<img class="art' + (o.cls ? " " + o.cls : "") + '" src="' + esc(u) + '"'
      + (o.w ? ' width="' + o.w + '"' : "")
      + (o.h ? ' height="' + o.h + '"' : "")
      + ' alt="' + esc(o.alt || "") + '" draggable="false"'
      + (o.alt ? "" : ' aria-hidden="true"')
      + ' loading="' + (o.eager ? "eager" : "lazy") + '" decoding="async">';
  }

  function css(u) { return u ? 'url("' + u + '")' : "none"; }

  return {
    plant:  function (id)  { return url(PLANT[id]); },
    book:   function (id)  { return url(BOOK[id]); },
    person: function (who) { return url(PERSON[who]); },
    place:  place,
    story:  function (k)   { return url(STORY[k]); },
    asset:  function (id)  { return url(ASSET[id]); },
    note:   function (id)  { return url(NOTE[id]); },
    img: img, css: css,
    count: 254
  };
})();
