// Summer Champs: in-event HUD (broadcast style). Events call these methods; input is routed back via onInput.
import { SAVE } from './sc-save.js';
const $ = (root, sel) => root.querySelector(sel);
export function createHUD(root, player, onInput, onPause){
  root.innerHTML = '';
  const el = document.createElement('div'); el.style.cssText = 'position:absolute;inset:0'; root.appendChild(el);
  let cfg = {}, cueT = 0, chipLabels = [];
  const H = {
    setup(c){
      cfg = c; chipLabels = Array.isArray(c.chips) ? c.chips.map(x => Array.isArray(x)? x[0] : x) : [];
      el.innerHTML = `
      <button class="btn abs hp" data-pause style="right:28px;top:28px;width:60px;height:60px;border:1px solid rgba(255,255,255,.22);display:flex;align-items:center;justify-content:center;gap:6px" aria-label="Pause"><span style="width:6px;height:22px;background:#fff"></span><span style="width:6px;height:22px;background:#fff"></span></button>
      <div class="abs" style="left:206px;top:28px;display:flex;height:60px;border-radius:4px;overflow:hidden"><div style="background:#F2B705;color:#0B1B3A;padding:0 16px;display:flex;align-items:center;font:800 32px 'Barlow Condensed'">${c.code}</div><div style="background:rgba(7,18,42,.92);padding:0 18px;display:flex;flex-direction:column;justify-content:center"><span class="C" style="font-weight:700;font-size:22px;line-height:1;letter-spacing:.04em">${c.name}</span><span data-sub style="font:600 12px/1.4 Barlow;letter-spacing:.16em;color:rgba(255,255,255,.7)">${c.sub || 'EVENT'}</span></div></div>
      <div class="abs" data-tr style="right:100px;top:28px;display:flex;border-radius:4px;overflow:hidden;height:80px"></div>
      ${c.ticker ? '<div class="abs" data-ticker style="left:28px;top:108px;width:290px;display:flex;flex-direction:column;gap:3px"></div>' : ''}
      ${c.rail ? '<div class="abs" style="left:470px;right:360px;top:54px;height:5px;background:rgba(7,18,42,.5)"><div data-rail style="width:0;height:5px;background:#F2B705"></div><span class="C" style="position:absolute;right:-4px;top:-26px;font-weight:700;font-size:15px;color:#0B1B3A">100</span></div>' : ''}
      ${c.meter ? `<div class="abs" style="left:50%;transform:translateX(-50%);bottom:28px;width:460px;display:flex;flex-direction:column;gap:8px"><span class="lbl">${c.meter}</span><div class="seg" data-meter>${'<span></span>'.repeat(14)}</div>${c.pads ? '<button class="btn abs hp" data-swap aria-label="Swap tap pads" style="width:56px;height:56px;border:1px solid rgba(255,255,255,.22);display:flex;align-items:center;justify-content:center;font:700 30px/1 Barlow;color:#fff;left:-72px;bottom:-11px">⇄</button>' : ''}</div>` : ''}
      ${c.approach ? '<div class="abs" style="left:50%;bottom:206px;transform:translateX(-50%);width:460px"><div style="position:relative;height:22px;background:rgba(7,18,42,.88);border-radius:3px"><span data-apz style="position:absolute;top:4px;bottom:4px;background:rgba(242,183,5,.45)"></span><span data-apf style="position:absolute;top:4px;bottom:4px;right:4px;background:rgba(229,72,77,.6)"></span><span data-apb style="position:absolute;top:-4px;bottom:-4px;width:4px;margin-left:-2px;background:#fff"></span><span data-apm style="position:absolute;top:-7px;width:14px;height:36px;margin-left:-7px;border-radius:3px;background:#fff;box-shadow:0 0 0 3px rgba(7,18,42,.6)"></span></div></div>' : ''}
      ${c.hops ? '<div class="abs hp" data-hopbox style="left:50%;top:116px;transform:translateX(-50%);padding:14px 18px 8px;display:flex;flex-direction:column;align-items:center;gap:6px;opacity:0;transition:opacity .2s"><svg data-hops width="480" height="96" viewBox="0 0 480 96" style="display:block;overflow:visible"><path data-hb d="" fill="none" stroke="rgba(255,255,255,.14)" stroke-width="18" stroke-linecap="butt"/><path data-hz d="" fill="none" stroke="#F2B705" stroke-width="18" stroke-linecap="butt"/><g data-hm></g><path data-hp d="" fill="none" stroke="#fff" stroke-width="5" stroke-linecap="round"/>'+[0,1,2].map(k => '<text data-hv'+k+' x="'+(k*160+80)+'" y="74" text-anchor="middle" style="font:800 22px Barlow Condensed;fill:#fff"></text>').join('')+'</svg><div style="display:flex;width:480px;justify-content:space-around"><span class="lbl" data-hl0>HOP</span><span class="lbl" data-hl1>STEP</span><span class="lbl" data-hl2>JUMP</span></div></div>' : ''}
      ${c.chips ? '<div class="abs" data-chips style="left:50%;top:116px;transform:translateX(-50%);display:flex;gap:6px"></div>' : ''}
      ${(() => { const DIAL = pos => `<div class="hp" data-dialbox style="${pos};transition:opacity .25s;padding:12px;display:flex;align-items:center;gap:14px"><div data-dial style="width:150px;height:150px;border-radius:50%;position:relative;display:flex;align-items:center;justify-content:center"><div style="width:114px;height:114px;border-radius:50%;background:#07122A;display:flex;flex-direction:column;align-items:center;justify-content:center"><span data-diall style="font:600 12px Barlow;letter-spacing:.18em" class="dim"></span></div><span data-needle style="position:absolute;left:50%;top:0;width:4px;height:50%;margin-left:-2px;background:#fff;transform-origin:50% 100%;opacity:0"></span></div></div>`, ANG = pos => '<div class="hp" data-angbox style="'+pos+';transition:opacity .25s;padding:12px 20px;display:flex;align-items:flex-end;gap:18px"><div style="width:150px;height:150px;position:relative;border-radius:0 150px 0 0;background:conic-gradient(from 0deg at 0% 100%,rgba(255,255,255,.14) 0 40deg,#F2B705 40deg 55deg,rgba(255,255,255,.14) 55deg 90deg,transparent 90deg)"><span data-angn style="position:absolute;left:0;bottom:0;width:148px;height:4px;margin-bottom:-2px;background:#fff;border-radius:2px;transform-origin:0 50%;transform:rotate(0deg)"></span></div><div style="display:flex;flex-direction:column;gap:4px"><span class="dim" style="font:600 12px Barlow;letter-spacing:.18em">ANGLE</span><span data-ang class="C" style="font-weight:800;font-size:56px;line-height:1">0°</span><span class="gold" style="font:600 12px Barlow;letter-spacing:.14em">GOLD 35–50°</span></div></div>';
        if (c.dial && c.angle) return `<div class="abs" data-gpair style="left:50%;top:116px;transform:translateX(-50%);transform-origin:50% 0;display:flex;gap:16px;align-items:stretch;transition:top .45s cubic-bezier(.2,.8,.2,1),transform .45s cubic-bezier(.2,.8,.2,1)">${DIAL('position:relative')}${ANG('position:relative')}</div>`;
        return (c.dial ? DIAL('position:absolute;left:50%;top:'+(c.chips && c.chips.length ? 190 : 116)+'px;transform:translateX(-50%)') : '') + (c.angle ? `<div class="abs" data-gpair style="left:50%;top:116px;transform:translateX(-50%);transform-origin:50% 0;display:flex;transition:top .45s cubic-bezier(.2,.8,.2,1),transform .45s cubic-bezier(.2,.8,.2,1),opacity .2s">${ANG('position:relative')}</div>` : ''); })()}
      ${c.action && !c.sliders ? '<div data-goldtag class="abs C" style="left:50%;bottom:'+(c.approach ? 240 : 206)+'px;transform:translateX(-50%);background:#F2B705;color:#0B1B3A;padding:4px 14px;border-radius:3px;font-weight:800;font-size:20px;letter-spacing:.08em;opacity:0;transition:opacity .15s;pointer-events:none">GOLD ZONE</div>' : ''}
      ${c.gauge ? '<div class="abs hp" style="right:28px;top:136px;bottom:'+(c.sliders ? 200 : 236)+'px;width:84px;padding:12px 0;display:flex;flex-direction:column;align-items:center;gap:6px"><span class="C" style="font-weight:700;font-size:16px">'+(typeof c.gauge === 'string' ? c.gauge : '10M')+'</span><div style="flex:1;width:14px;background:rgba(255,255,255,.18);position:relative;border-radius:2px"><span data-gz style="position:absolute;left:0;right:0;bottom:0;height:30%;background:#F2B705;border-radius:2px"></span><span data-gm style="position:absolute;left:-18px;top:0;border-top:10px solid transparent;border-bottom:10px solid transparent;border-left:14px solid #fff;margin-top:-10px"></span></div><span class="C" style="font-weight:700;font-size:16px;color:#8FD3FF">WATER</span></div>' : ''}
      ${c.power ? '<div data-powerbox class="abs" style="left:50%;bottom:28px;transform:translateX(-50%);width:460px;display:none;flex-direction:column;align-items:center;gap:8px"><span class="lbl">POWER · KEEP IT ABOVE THE GOLD LINE</span><div style="position:relative;width:100%;height:36px;background:rgba(7,18,42,.88);border-radius:3px"><span data-pw style="position:absolute;left:6px;top:6px;bottom:6px;width:0;background:#fff;border-radius:2px"></span><span data-pthr style="position:absolute;top:-8px;bottom:-8px;width:6px;margin-left:-3px;background:#F2B705;border-radius:3px;left:50%;box-shadow:0 0 0 3px rgba(242,183,5,.3)"></span></div></div>' : ''}
      ${c.balance ? '<div data-balbox class="abs" style="display:none;left:50%;bottom:28px;transform:translateX(-50%);width:460px;display:flex;flex-direction:column;align-items:center;gap:8px"><span class="lbl">BALANCE</span><div style="position:relative;width:100%;height:36px;background:rgba(7,18,42,.88);border-radius:3px"><span style="position:absolute;left:34%;width:32%;top:6px;bottom:6px;background:#F2B705"></span><span style="position:absolute;left:8px;top:6px;bottom:6px;width:14%;background:rgba(229,72,77,.55)"></span><span style="position:absolute;right:8px;top:6px;bottom:6px;width:14%;background:rgba(229,72,77,.55)"></span><span data-bal style="position:absolute;left:50%;top:-8px;width:6px;height:52px;margin-left:-3px;background:#fff;border-radius:3px"></span></div></div>' : ''}
      ${c.bout ? `<div class="abs" data-boutbox style="width:max-content;white-space:nowrap;left:50%;top:108px;transform:translateX(-50%);transition:left .6s cubic-bezier(.2,.8,.2,1),transform .6s cubic-bezier(.2,.8,.2,1),top .6s cubic-bezier(.2,.8,.2,1);display:flex;height:84px;border-radius:4px;overflow:hidden"><div style="width:12px;background:${c.bout[0].kit.color}"></div><div style="background:rgba(7,18,42,.94);padding:0 18px;display:flex;align-items:center;font:800 28px 'Barlow Condensed'">${c.bout[0].name}</div><div data-s0 style="background:#F2B705;color:#0B1B3A;width:84px;display:flex;align-items:center;justify-content:center;font:800 60px/1 'Barlow Condensed'">0</div><div style="background:#fff;color:#0B1B3A;padding:0 16px;display:flex;flex-direction:column;align-items:center;justify-content:center"><span data-bt class="C" style="font-weight:700;font-size:26px;line-height:1">1:30</span><span style="font:600 11px Barlow;letter-spacing:.14em">FIRST TO 5</span></div><div data-s1 style="background:rgba(7,18,42,.94);width:84px;display:flex;align-items:center;justify-content:center;font:800 60px/1 'Barlow Condensed'">0</div><div style="background:rgba(7,18,42,.94);padding:0 18px;display:flex;align-items:center;font:800 28px 'Barlow Condensed'">${c.bout[1].name}</div><div style="width:12px;background:${c.bout[1].kit.color}"></div></div>` : ''}
      ${c.target ? '<div class="abs hp" style="right:28px;top:124px;width:200px;padding:12px;display:flex;flex-direction:column;align-items:center;gap:8px"><span class="dim" style="font:600 12px Barlow;letter-spacing:.18em">TARGET</span><div data-tgt style="width:170px;height:170px;border-radius:50%;background:radial-gradient(circle,#F2B705 0 18%,#D9434F 18% 36%,#2F7FD1 36% 54%,#1E1E1E 54% 72%,#fff 72% 100%);position:relative"></div></div>' : ''}
      ${c.wind !== undefined ? `<div class="abs hp" style="left:28px;top:108px;height:60px;display:flex;align-items:center;gap:14px;padding:0 16px"><span class="dim" style="font:600 12px Barlow;letter-spacing:.18em">WIND</span><span data-wa class="C gold" style="font-weight:800;font-size:34px">${c.wind < 0 ? '←' : '→'}</span><span data-wv class="C" style="font-weight:800;font-size:28px">${Math.abs(c.wind).toFixed(1)}</span></div>` : ''}
      ${c.draw ? '<div class="abs" style="left:50%;bottom:36px;transform:translateX(-50%);width:460px;display:flex;flex-direction:column;gap:8px;align-items:center"><span class="lbl">DRAW · STOP IN THE GOLD</span><div style="position:relative;width:100%;height:34px;background:rgba(7,18,42,.88);border-radius:3px;overflow:hidden"><span style="position:absolute;left:70%;width:22%;top:0;bottom:0;background:rgba(242,183,5,.35)"></span><span data-draw style="position:absolute;left:0;top:8px;bottom:8px;width:0;background:#fff"></span></div></div><div data-ret class="abs" style="left:50%;top:50%;width:110px;height:110px;margin:-55px 0 0 -55px;border-radius:50%;border:3px solid #fff;display:none;pointer-events:none"><span style="position:absolute;left:50%;top:-14px;bottom:-14px;width:2px;margin-left:-1px;background:#fff"></span><span style="position:absolute;top:50%;left:-14px;right:-14px;height:2px;margin-top:-1px;background:#fff"></span><span style="position:absolute;left:50%;top:50%;width:10px;height:10px;margin:-5px 0 0 -5px;border-radius:50%;background:#F2B705"></span></div>' : ''}
      ${c.sliders ? `<div class="abs" data-sliders style="left:28px;bottom:28px;display:flex;flex-direction:column;gap:12px;opacity:0;pointer-events:none;transition:opacity .25s">${[['tuck','TUCK','TUCKED','STRAIGHT',1],['twist','TWIST','◀ SLOW','FAST ▶',0],['spin','SPIN','◀ SLOW','FAST ▶',0]].map(([id, l, lo, hi, one]) => `<div style="display:flex;align-items:center;gap:12px"><span class="C" style="width:92px;font-weight:800;font-size:28px;text-shadow:0 1px 4px rgba(0,0,0,.6)">${l}</span><div data-slider="${id}" ${one ? 'data-one="1"' : ''} style="position:relative;width:380px;height:72px;border-radius:6px;background:rgba(7,18,42,.84);border:1px solid rgba(255,255,255,.25);touch-action:none">${one ? '' : '<span style="position:absolute;left:50%;top:10px;bottom:10px;width:2px;background:rgba(255,255,255,.35)"></span>'}<span class="dim C" style="position:absolute;left:78px;top:50%;transform:translateY(-50%);font-weight:700;font-size:20px">${lo}</span><span class="dim C" style="position:absolute;right:78px;top:50%;transform:translateY(-50%);font-weight:700;font-size:20px">${hi}</span><span data-th style="position:absolute;top:4px;width:64px;height:62px;border-radius:5px;background:#F2B705;box-shadow:0 0 0 4px rgba(242,183,5,.3)"></span></div></div>`).join('')}</div>` : ''}
      ${c.pads && !c.meter ? '<button class="btn abs hp" data-swap aria-label="Swap tap pads" style="width:56px;height:56px;border:1px solid rgba(255,255,255,.22);display:flex;align-items:center;justify-content:center;font:700 30px/1 Barlow;color:#fff;left:210px;bottom:28px">⇄</button>' : ''}
      ${c.pads ? `<button class="btn pad" data-in="L" style="left:28px"><b>L</b><i>${c.pads}</i></button><button class="btn pad" data-in="R" style="right:28px"><b>R</b><i>${c.pads}</i></button>` : ''}
      ${c.action ? `<button class="btn act off" data-in="action" style="${c.sliders ? 'left:28px;bottom:28px;width:484px;height:240px;transform:none' : (c.meter || c.power) ? 'bottom:98px;height:100px' : ''}"><b data-al>${c.action.label}</b><i data-as>${c.action.sub}</i></button>` : ''}
      ${c.buttons ? `<div class="abs" style="left:28px;bottom:28px;display:flex;${c.buttons.leftLabel ? 'flex-direction:column' : ''};gap:8px">${c.buttons.leftLabel ? `<span class="lbl">${c.buttons.leftLabel}</span>` : ''}${c.buttons.left.map(([id, l]) => `<button class="btn hb" data-btn="${id}" style="${c.buttons.leftLabel ? '' : 'width:170px;height:150px'}">${l}</button>`).join('')}</div>` : ''}
      ${c.buttons && c.buttons.right ? `<div class="abs" style="right:28px;bottom:28px;display:flex;flex-direction:column;align-items:flex-end;gap:8px"><span class="lbl">${c.buttons.rightLabel}</span>${c.buttons.right.map(([id, l]) => `<button class="btn hb w" data-btn="${id}">${l}</button>`).join('')}</div>` : ''}
      ${c.drag ? '<div class="abs" data-drag style="right:28px;bottom:28px;width:230px;height:230px;border-radius:50%;border:3px dashed rgba(255,255,255,.75);background:rgba(7,18,42,.55);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:2px;touch-action:none"><span class="C gold" style="font-weight:800;font-size:54px;line-height:1">↓</span><span class="C" style="font-weight:800;font-size:26px">DRAG DOWN</span><span class="dim" style="font:600 13px Barlow;letter-spacing:.16em">LET GO TO SHOOT</span></div>' : ''}
      <div class="cue" data-cue style="opacity:0"></div>`;
      $(el, '[data-pause]').onclick = onPause;
      el.querySelectorAll('[data-in]').forEach(b => { const k = b.dataset.in;
        b.addEventListener('pointerdown', e => { e.preventDefault(); onInput(k, true); });
        b.addEventListener('pointerup', () => onInput(k, false)); b.addEventListener('pointerleave', () => k==='action' && onInput(k, false)); });
      el.querySelectorAll('[data-btn]').forEach(b => b.addEventListener('pointerdown', e => { e.preventDefault(); onInput('btn', true, b.dataset.btn); }));
      const padL = $(el, '[data-in="L"]'), applySwap = () => { if (!padL) return; const on = SAVE.get('padsRight', false); padL.style.left = on ? 'auto' : '28px'; padL.style.right = on ? '210px' : ''; const cu = $(el, '[data-cue]'); if (cu) cu.style.left = cu.style.right = (on ? 392 : 270)+'px'; };
      applySwap(); const sw = $(el, '[data-swap]'); if (sw) sw.addEventListener('pointerdown', e => { e.preventDefault(); e.stopPropagation(); SAVE.set('padsRight', !SAVE.get('padsRight', false)); applySwap(); });
      const dz = $(el, '[data-drag]'); if (dz){ let y0 = null;
        dz.addEventListener('pointerdown', e => { dz.setPointerCapture(e.pointerId); y0 = e.clientY; onInput('drag', true, { phase:'start', dy:0 }); });
        dz.addEventListener('pointermove', e => { if (y0 === null) return; const sc = parseFloat(getComputedStyle(document.getElementById('stage')).getPropertyValue('--s')) || 1; onInput('drag', true, { phase:'move', dy:(e.clientY-y0)/sc }); });
        const up = () => { if (y0 === null) return; y0 = null; onInput('drag', false, { phase:'end' }); }; dz.addEventListener('pointerup', up); dz.addEventListener('pointercancel', up); }
      el.querySelectorAll('[data-slider]').forEach(tr => { const id = tr.dataset.slider, one = !!tr.dataset.one, spring = !!tr.dataset.spring, th = tr.querySelector('[data-th]'); let drag = false;
        tr._set = (v, silent) => { tr._v = v; th.style.left = (4 + (one ? 1-v : (v+1)/2)*(tr.clientWidth - 72))+'px'; if (!silent) onInput('slider', true, { id, v }); };
        const from = e => { const r = tr.getBoundingClientRect(), sc = r.width/tr.offsetWidth; const u = Math.max(0, Math.min(1, (e.clientX - r.left - 36*sc)/(r.width - 72*sc))); return one ? 1-u : u*2 - 1; };
        tr.addEventListener('pointerdown', e => { e.preventDefault(); tr.setPointerCapture(e.pointerId); drag = true; th.style.transition = 'none'; tr._set(from(e)); });
        tr.addEventListener('pointermove', e => { if (drag) tr._set(from(e)); });
        const up = () => { if (!drag) return; drag = false; if (spring){ th.style.transition = 'left .18s'; tr._set(0); } }; tr.addEventListener('pointerup', up); tr.addEventListener('pointercancel', up);
        tr._set(0, true); });
      { const cu = $(el, '[data-cue]'), cb = c.cueBottom ?? (c.approach ? 280 : c.action && !c.sliders ? 214 : (c.meter || c.draw || c.power) ? 108 : 36); cu.style.bottom = cb+'px'; { const m = (c.pads && SAVE.get('padsRight', false) ? 392 : 270)+'px'; cu.style.left = m; cu.style.right = m; } H._cue = cu; cu.style.textWrap = 'balance'; if (c.cueSize) cu.style.fontSize = c.cueSize+'px'; }
      if (c.stat) H.stat(...c.stat);
      if (c.clock) H.clock(0);
      if (c.chips) H.chips(c.chips.map(() => 0));
    },
    sub(t){ const s = $(el, '[data-sub]'); if (s) s.textContent = t; },
    stat(label, value){ const tr = $(el, '[data-tr]'); let v = $(tr, '[data-sv]'); if (!v){ tr.insertAdjacentHTML('beforeend', `<div style="background:#fff;color:#0B1B3A;padding:0 22px;display:flex;flex-direction:column;justify-content:center;align-items:flex-end;min-width:130px"><span data-sl style="font:600 12px Barlow;letter-spacing:.16em"></span><span data-sv class="C" style="font-weight:700;font-size:46px;line-height:1;font-variant-numeric:tabular-nums"></span></div>`); v = $(tr, '[data-sv]'); } $(tr, '[data-sl]').textContent = label; v.textContent = value; },
    stat2(label, value){ const tr = $(el, '[data-tr]'); let b = $(tr, '[data-s2]'); if (!b){ tr.insertAdjacentHTML('afterbegin', `<div data-s2 style="background:rgba(7,18,42,.92);padding:0 18px;display:flex;flex-direction:column;justify-content:center;gap:2px"></div>`); b = $(tr, '[data-s2]'); } b.innerHTML = `<span style="font:600 12px Barlow;letter-spacing:.16em;color:rgba(255,255,255,.65)">${label}</span><span class="C" style="font-weight:700;font-size:22px;line-height:1">${value}</span>`; },
    attempt(...args){ H.resetGauges(); return H._attempt(...args); },
    _attempt(n, total){ const tr = $(el, '[data-tr]'); let b = $(tr, '[data-att]'); if (!b){ tr.insertAdjacentHTML('afterbegin', '<div data-att style="background:rgba(7,18,42,.92);padding:0 18px;display:flex;flex-direction:column;justify-content:center;gap:6px"></div>'); b = $(tr, '[data-att]'); }
      b.innerHTML = `<span style="font:600 12px Barlow;letter-spacing:.16em;color:rgba(255,255,255,.65)">${cfg.id==='archery' ? 'ARROW' : 'GO'} ${n} OF ${total}</span><span style="display:flex;gap:6px">${Array.from({length:total}, (_, i) => `<span style="width:14px;height:14px;border-radius:50%;${i < n-1 ? 'background:#fff' : i === n-1 ? 'background:#F2B705' : 'border:2px solid rgba(255,255,255,.5)'}"></span>`).join('')}</span>`; },
    clock(t){ const tr = $(el, '[data-tr]'); let c = $(tr, '[data-clk]'); if (!c){ tr.insertAdjacentHTML('beforeend', '<div data-clk class="C" style="background:#fff;color:#0B1B3A;padding:0 22px;display:flex;align-items:center;justify-content:flex-end;min-width:170px;font-weight:700;font-size:66px;line-height:1;font-variant-numeric:tabular-nums"></div>'); c = $(tr, '[data-clk]'); } c.textContent = t.toFixed(2); },
    cue(text, cls=''){ const c = $(el, '[data-cue]'); if (!c) return; c.textContent = text; c.className = 'cue '+cls; c.style.opacity = text ? 1 : 0; clearTimeout(cueT); if (text) cueT = setTimeout(() => c.style.opacity = 0, 1300); },
    action(state, label, sub){ const sl = $(el, '[data-sliders]'); if (sl){ const on = state === 'off'; sl.style.opacity = on ? 1 : 0; sl.style.pointerEvents = on ? 'auto' : 'none'; } const a = $(el, '[data-in="action"]'); if (!a) return; a.className = 'btn act '+state; if (label) $(a, '[data-al]').textContent = label; if (sub) $(a, '[data-as]').textContent = sub; },
    pad(side){ const p = $(el, `[data-in="${side}"]`); if (!p) return; p.classList.add('on'); clearTimeout(p._t); p._t = setTimeout(() => p.classList.remove('on'), 110); },
    meter(_, f){ const m = $(el, '[data-meter]'); if (!m) return; const n = Math.round(f*14); [...m.children].forEach((s, i) => s.classList.toggle('f', i < n)); },
    rail(f){ const r = $(el, '[data-rail]'); if (r) r.style.width = Math.min(100, f*100)+'%'; },
    ticker(rows){ const t = $(el, '[data-ticker]'); if (!t) return; t.innerHTML = rows.map((r, i) => `<div class="tk${r.me ? ' me' : ''}"><span class="r">${i+1}</span><span class="c" style="background:${r.color}"></span><span class="n">${r.name}</span><span class="g">${r.gap}</span></div>`).join(''); },
    chips(arr){ const c = $(el, '[data-chips]'); if (!c) return; const items = arr.map((x, i) => Array.isArray(x) ? x : [chipLabels[i], x]);
      c.innerHTML = items.map(([l, s]) => `<div class="C" style="min-width:150px;height:56px;padding:0 16px;border-radius:4px;display:flex;align-items:center;justify-content:center;gap:10px;font-weight:800;font-size:26px;${s===1 ? 'background:#F2B705;color:#0B1B3A;box-shadow:0 0 0 4px rgba(242,183,5,.35)' : s===2 ? 'background:rgba(7,18,42,.9)' : 'border:1px solid rgba(255,255,255,.35);background:rgba(7,18,42,.55);color:rgba(255,255,255,.7)'}">${l}${s===2 ? ' <span style="font:800 12px Barlow;color:#0B1B3A;background:#fff;padding:2px 6px;border-radius:2px">✓</span>' : ''}</div>`).join(''); },
    dial(f, zone, label, outer){ const d = $(el, '[data-dial]'); if (!d) return; const B = 'rgba(255,255,255,.14)', O = 'rgba(255,255,255,.42)', z0 = zone[0]*360, z1 = Math.min(1,zone[1])*360; d.style.background = outer ? `conic-gradient(${B} 0 ${outer[0]*360}deg,${O} ${outer[0]*360}deg ${z0}deg,#F2B705 ${z0}deg ${z1}deg,${O} ${z1}deg ${outer[1]*360}deg,${B} ${outer[1]*360}deg 360deg)` : `conic-gradient(${B} 0 ${z0}deg,#F2B705 ${z0}deg ${z1}deg,${B} ${z1}deg 360deg)`; const nd = $(el, '[data-needle]'); nd.style.transform = `rotate(${f*360}deg)`; nd.style.opacity = 1; if (label) $(el, '[data-diall]').textContent = label; },
    angle(r){ const a = $(el, '[data-ang]'); if (!a) return; const d = Math.round(r*57.3); a.textContent = d+'°'; a.style.color = d >= 35 && d <= 50 ? '#F2B705' : '#fff'; const n = $(el, '[data-angn]'); if (n) n.style.transform = `rotate(${-d}deg)`; },
    gauge(f, z){ const m = $(el, '[data-gm]'); if (!m) return; m.style.top = (100 - f*100)+'%'; $(el, '[data-gz]').style.height = (z*100)+'%'; },
    btn(id, state){ const b = $(el, `[data-btn="${id}"]`); if (!b) return; b.classList.toggle('on', state === 'on'); if (state === 'flash'){ b.classList.add('flash'); setTimeout(() => b.classList.remove('flash'), 180); } },
    reticle(x, y){ const r = $(el, '[data-ret]'); if (!r) return; if (x === null){ r.style.display = 'none'; return; } r.style.display = 'block'; r.style.transform = `translate(${x*110}px,${y*110}px)`; },
    draw(f){ const d = $(el, '[data-draw]'); if (d){ d.style.width = (f*100)+'%'; d.style.background = f > 0.7 && f < 0.92 ? '#F2B705' : '#fff'; } },
    targetHit(x, y){ const t = $(el, '[data-tgt]'); if (t) t.insertAdjacentHTML('beforeend', `<span style="position:absolute;left:${85+x*85-5}px;top:${85+y*85-5}px;width:10px;height:10px;border-radius:50%;background:#0B1B3A;box-shadow:0 0 0 2px #fff"></span>`); },
    balance(b, out){ const m = $(el, '[data-bal]'); if (!m) return; m.style.left = (50 + Math.max(-1, Math.min(1, b))*46)+'%'; m.style.background = out ? '#FF6B6F' : '#fff'; },
    bout(sc, t){ const a = $(el, '[data-s0]'); if (!a) return; a.textContent = sc[0]; $(el, '[data-s1]').textContent = sc[1]; $(el, '[data-bt]').textContent = Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2, '0'); },
    board(){},
    hopMark(seg, p){ const g = $(el, '[data-hm]'); if (!g) return; const W = 160, B = 86, R = 70, a = Math.PI*Math.min(1, Math.max(0, p)), x = seg*W + W/2 - (W/2)*Math.cos(a), y = B - R*Math.sin(a); let nx = x - (seg*W + W/2), ny = (y - B)*(W/2)/R; const l = Math.hypot(nx, ny) || 1; nx /= l; ny /= l; g.insertAdjacentHTML('beforeend', '<path d="M'+(x - nx*11).toFixed(1)+' '+(y - ny*11).toFixed(1)+' L'+(x + nx*11).toFixed(1)+' '+(y + ny*11).toFixed(1)+'" stroke="#fff" stroke-width="2" opacity=".9"/>'); },
    hopVal(k, text, good){ const t = $(el, '[data-hv'+k+']'); if (!t) return; t.textContent = text || ''; t.style.fill = good === true ? '#F2B705' : good === false ? '#FF6B6F' : '#fff'; },
    hops(seg, p, zone){ const s = $(el, '[data-hops]'); if (!s) return; const box = $(el, '[data-hopbox]'); if (box) box.style.opacity = zone[1] > zone[0] ? 1 : 0;
      const W = 160, B = 86, R = 70, pt = (k, u) => { const a = Math.PI*Math.min(1, Math.max(0, u)); return [k*W + W/2 - (W/2)*Math.cos(a), B - R*Math.sin(a)]; };
      const line = (k, a, b, n = 24) => { let d = ''; for (let i=0;i<=n;i++){ const u = a + (b - a)*i/n, kk = u > 1 ? k+1 : k, uu = u > 1 ? u-1 : u, [x, y] = pt(kk, uu); d += (i ? 'L' : 'M')+x.toFixed(1)+' '+y.toFixed(1)+' '; } return d; };
      const hb = $(el, '[data-hb]'); if (!hb.getAttribute('d')) hb.setAttribute('d', [0,1,2].map(k => line(k, 0, 1)).join(''));
      const z = $(el, '[data-hz]'), zk = zone.join(','); if (zone[1] > zone[0] && z.dataset.k !== zk){ z.dataset.k = zk; z.setAttribute('d', [0,1].map(k => line(k, zone[0], Math.min(zone[1], 1.1), 12)).join('')); }
      const u = Math.min(1, Math.max(0, p)), [x, y] = pt(seg, u), cx = seg*W + W/2; let nx = x - cx, ny = (y - B)*(W/2)/R; const nl = Math.hypot(nx, ny) || 1; nx /= nl; ny /= nl;
      $(el, '[data-hp]').setAttribute('d', 'M'+(x - nx*14).toFixed(1)+' '+(y - ny*14).toFixed(1)+' L'+(x + nx*14).toFixed(1)+' '+(y + ny*14).toFixed(1)); [0,1,2].forEach(k => { const l = $(el, '[data-hl'+k+']'); if (l) l.style.color = k === seg ? '#F2B705' : k < seg ? '#fff' : 'rgba(255,255,255,.55)'; }); },
    gaugeFocus(w){ const d = $(el, '[data-dialbox]'), a = $(el, '[data-angbox]'); if (!d || !a) return; d.style.opacity = w === 'angle' ? .35 : 1; a.style.opacity = w === 'dial' ? .35 : 1; },
    goldTag(on){ const g = $(el, '[data-goldtag]'); if (g) g.style.opacity = on ? 1 : 0; },
    gaugeShow(on){ const p = $(el, '[data-gpair]'); if (p) p.style.opacity = on ? 1 : 0; },
    gaugeDock(on){ const p = $(el, '[data-gpair]'); if (!p) return; p.style.top = on ? '492px' : '116px'; p.style.transform = on ? 'translateX(-50%) scale(.62)' : 'translateX(-50%)'; if (on) H.gaugeFocus(null); },
    resetGauges(){ const q = k => $(el, k);
      if (q('[data-meter]')) H.meter(null, 0);
      if (q('[data-ang]')) H.angle(0);
      if (q('[data-dial]') && cfg.dial){ const n = q('[data-needle]'); if (n){ n.style.transform = 'rotate(0deg)'; n.style.opacity = 0; } const l = q('[data-diall]'); if (l) l.textContent = ''; }
      H.gaugeDock(false); H.gaugeFocus(null); H.goldTag(false); if (q('[data-hops]')){ H.hops(0, 0, [0,0]); [0,1,2].forEach(k => H.hopVal(k, '')); q('[data-hm]').innerHTML = ''; }
      if (q('[data-draw]')) H.draw(0);
      if (q('[data-pw]')) H.power(0, 0.5);
      if (q('[data-bal]')) H.balance(0, false);
      if (q('[data-apm]')) q('[data-apm]').style.left = '0%';
      if (q('[data-gm]')) q('[data-gm]').style.top = '0%';
      H.reticle(null); },
    approach(f, z0, b, hot){ const m = $(el, '[data-apm]'); if (!m) return; const P = v => (Math.max(0, Math.min(1, v))*100)+'%'; m.style.left = P(f); m.style.background = hot ? '#F2B705' : '#fff'; const z = $(el, '[data-apz]'); z.style.left = P(z0); z.style.width = 'calc('+P(b)+' - '+P(z0)+')'; z.style.background = hot ? 'rgba(242,183,5,.85)' : 'rgba(242,183,5,.45)'; $(el, '[data-apb]').style.left = P(b); $(el, '[data-apf]').style.left = P(b);  },
    boutSide(side){ const b = $(el, '[data-boutbox]'); if (!b) return; if (side==='left'){ b.style.left = '28px'; b.style.transform = 'none'; b.style.top = '300px'; } else if (side==='right'){ b.style.left = 'calc(100% - 28px)'; b.style.transform = 'translateX(-100%)'; b.style.top = '300px'; } else { b.style.left = '50%'; b.style.transform = 'translateX(-50%)'; b.style.top = '108px'; } },
    focusBtns(ids){ el.querySelectorAll('[data-btn^="a"]').forEach(b => { const on = ids && ids.includes(b.dataset.btn); b.classList.toggle('on', !!on); }); },
    marker(x, y){ let m = $(el, '[data-mk]'); if (!m){ el.insertAdjacentHTML('beforeend', '<div data-mk class="abs" style="width:46px;height:46px;margin:-23px 0 0 -23px;border-radius:50%;border:3px solid rgba(255,107,111,.85);box-shadow:0 0 0 6px rgba(255,107,111,.18),0 0 18px rgba(255,107,111,.45);pointer-events:none;transition:opacity .12s;opacity:0;display:flex;align-items:center;justify-content:center"><span style="width:10px;height:10px;border-radius:50%;background:#FF6B6F"></span></div>'); m = $(el, '[data-mk]'); } if (x == null){ m.style.opacity = 0; return; } m.style.left = x+'px'; m.style.top = y+'px'; m.style.opacity = 1; },
    power(f, thr){ const w = $(el, '[data-pw]'); if (!w) return; w.style.width = 'calc('+(f*100)+'% - 12px)'; w.style.background = f >= thr ? '#F2B705' : '#fff'; $(el, '[data-pthr]').style.left = (thr*100)+'%'; },
    liftStage(st){ const p = $(el, '[data-powerbox]'), b = $(el, '[data-balbox]'); if (p) p.style.display = st==='lift' ? 'flex' : 'none'; if (b) b.style.display = st==='hold' ? 'flex' : 'none'; },
    choose(list, title){ const old = $(el, '[data-choose]'); if (old) old.remove(); const cu = $(el, '[data-cue]'); if (cu) cu.style.visibility = list ? 'hidden' : ''; if (!list) return;
      el.insertAdjacentHTML('beforeend', `<div data-choose class="abs" style="left:0;right:0;top:196px;display:flex;flex-direction:column;align-items:center;gap:16px;z-index:5;animation:fo .25s ease-out"><span class="C" style="font-weight:800;font-size:40px;text-shadow:0 2px 8px rgba(0,0,0,.6)">${title}</span><div style="display:flex;gap:16px">${list.map((o, i) => `<button class="btn" data-pick="${o.id}" style="width:230px;height:190px;border-radius:6px;background:rgba(7,18,42,.92);border:2px solid rgba(255,255,255,.3);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px"><span class="gold" style="font:700 14px Barlow;letter-spacing:.2em">${o.top}</span><span class="C" style="font-weight:800;font-size:66px;line-height:1">${o.w}</span><span class="dim" style="font:600 14px Barlow;letter-spacing:.14em">${o.sub}</span></button>`).join('')}</div></div>`);
      el.querySelectorAll('[data-pick]').forEach(b => b.addEventListener('pointerdown', e => { e.preventDefault(); onInput('btn', true, b.dataset.pick); })); },
    wind(v){ const a = $(el, '[data-wa]'), n = $(el, '[data-wv]'); if (!a) return; a.textContent = v < 0 ? '←' : '→'; n.textContent = Math.abs(v).toFixed(1); },
    sliderVal(id){ const tr = $(el, `[data-slider="${id}"]`); return tr ? tr._v || 0 : 0; },
    slider(id, v){ const tr = $(el, `[data-slider="${id}"]`); if (tr && tr._set) tr._set(v, true); },
  };
  return H;
}
