// One-off converter: Claude Design template (Ember Bay.dc.html) -> js/eb-view.js.
// The design ran on Claude Design's React runtime (support.js). The arcade build has no runtime:
// this turns the screen markup into a plain function view(v, on) that returns an HTML string,
// which js/eb-dom.js morphs into the page. Run it again only if the design is re-exported:
//   node games/ember-bay/tools/dc-to-view.mjs "<path to Ember Bay.dc.html>" games/ember-bay/js/eb-view.js
// Template syntax handled: {{ path }} in text and attributes, <sc-if value>, <sc-for list as>,
// onXxx="{{ fn }}" (-> data-on-xxx, dispatched by eb-dom.js), ref="{{ fn }}" (-> data-ref + data-keep).
import fs from 'node:fs';

const [src, out] = process.argv.slice(2);
const html = fs.readFileSync(src, 'utf8');
// Only the screens: after the two render hosts (city + minigame), up to the static back link.
const a = html.indexOf('>', html.indexOf('ref="{{ mgRef }}"')) + 1 + '</div>'.length;
const b = html.indexOf('<a href="../../index.html"');
if (a < 20 || b < a) throw new Error('markers not found');
const body = html.slice(a, b).replace(/<!--[\s\S]*?-->/g, '');

const EVT = { Click: 'click', PointerDown: 'pointerdown', PointerUp: 'pointerup', PointerLeave: 'pointerleave', PointerCancel: 'pointercancel', Change: 'input', ContextMenu: 'contextmenu' };
const VOID = new Set(['input', 'img', 'br', 'meta', 'link', 'hr']);
const scope = [];
const expr = s => {
  s = s.trim();
  if (s === 'true' || s === 'false' || /^-?\d/.test(s)) return s;
  const head = s.split('.')[0];
  return scope.includes(head) ? s : 'v.' + s;
};
const lit = s => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
const interp = (s, fn) => lit(s).replace(/\{\{([^}]+)\}\}/g, (_, x) => '${' + fn + '(' + expr(x) + ')}');

let js = '', ifN = 0;
const ifStack = []; // { depth, key, n }
let depth = 0;
const re = /<\/?([a-zA-Z][\w-]*)((?:\s+[^\s=>]+(?:="[^"]*")?)*)\s*\/?>|([^<]+)/g;
let m;
while ((m = re.exec(body))) {
  const [tok, tag, attrs, text] = m;
  if (text !== undefined) { if (/^\s*$/.test(text) && text.includes('\n')) continue; js += interp(text.replace(/\s*\n\s*/g, ' '), 'e'); continue; }
  const close = tok.startsWith('</');
  const A = {}; (attrs || '').replace(/([^\s=]+)(?:="([^"]*)")?/g, (_, k, v) => (A[k] = v ?? ''));
  const bind = v => (v.match(/^\{\{([^}]+)\}\}$/) || [])[1];
  if (tag === 'sc-if') {
    if (close) { js += '` : \'\'}'; ifStack.pop(); }
    else { js += '${(' + expr(bind(A.value)) + ') ? `'; ifStack.push({ depth, key: 'i' + ifN++, n: 0 }); }
    continue;
  }
  if (tag === 'sc-for') {
    if (close) { js += '`).join(\'\')}'; scope.pop(); }
    else { js += '${(' + expr(bind(A.list)) + ' || []).map(' + A.as + ' => `'; scope.push(A.as); }
    continue;
  }
  if (close) { depth--; js += '</' + tag + '>'; continue; }
  let s = '<' + tag;
  const top = ifStack[ifStack.length - 1];
  if (top && top.depth === depth) s += ' data-k="' + top.key + String.fromCharCode(97 + top.n++) + '"';
  if (A.onPointerUp && !A.onPointerCancel) A.onPointerCancel = A.onPointerUp; // a cancelled touch must release too
  for (const [k, v] of Object.entries(A)) {
    if (k.startsWith('hint-') || k === 'data-screen-label') continue;
    const on = k.match(/^on([A-Z]\w+)$/);
    if (on) { s += ' data-on-' + (EVT[on[1]] || on[1].toLowerCase()) + '="${on(' + expr(bind(v)) + ')}"'; continue; }
    if (k === 'ref') { s += ' data-keep data-ref="${on(' + expr(bind(v)) + ')}"'; continue; }
    s += ' ' + k + '="' + interp(v, 'q') + '"';
  }
  s += '>';
  js += s;
  if (!VOID.has(tag)) depth++;
}

fs.writeFileSync(out, `// GENERATED by tools/dc-to-view.mjs from the Claude Design file — edit the design or this file by hand, not both.
// view(v, on): v = the values from EmberBay.vals(), on(fn) registers a handler and returns its id.
const e = x => String(x ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const q = x => e(x).replace(/"/g, '&quot;');
export function view(v, on) {
  return \`${js}\`;
}
`);
console.log('wrote', out, (js.length / 1024).toFixed(1) + ' KB,', ifN, 'if-blocks');
