// One-off converter: Claude Design template (Blink Lab 3D v3.dc.html) -> js/bl-view.js.
// Adapted from games/ember-bay/tools/dc-to-view.mjs. The design ran on Claude Design's React runtime
// (support.js); the arcade build has no runtime. This turns the template into view(v, on), a function
// that returns an HTML string, which js/bl-dom.js morphs into #ui. Run it again only if the design is
// re-exported:
//   node games/portal-lab/tools/dc-to-view.mjs "games/portal-lab/research/Blink Lab tablet design/Blink Lab 3D v3.dc.html" games/portal-lab/js/bl-view.js
// Template syntax handled: {{ path }} in text and attributes, <sc-if value>, <sc-for list as>,
// onXxx="{{ fn }}" (-> data-on-xxx, dispatched by bl-dom.js), ref="{{ fn }}" (-> data-ref + data-keep),
// style-active="css" (-> a generated class with an :active rule, exported as `css`).
import fs from 'node:fs';

const [src, out] = process.argv.slice(2);
const html = fs.readFileSync(src, 'utf8');
const a = html.indexOf('</helmet>') + '</helmet>'.length;
const b = html.indexOf('</x-dc>');
if (a < 20 || b < a) throw new Error('markers not found');
const body = html.slice(a, b).replace(/<!--[\s\S]*?-->/g, '');

const EVT = { Click: 'click', PointerDown: 'pointerdown', PointerUp: 'pointerup', PointerMove: 'pointermove', PointerLeave: 'pointerleave', PointerCancel: 'pointercancel', Change: 'input', ContextMenu: 'contextmenu' };
const VOID = new Set(['input', 'img', 'br', 'meta', 'link', 'hr']);
const scope = [];
const expr = s => {
  s = s.trim();
  if (s === 'true' || s === 'false' || /^-?\d/.test(s)) return s;
  const head = s.split('.')[0];
  return scope.includes(head) ? s : 'v.' + s;
};
const lit = s => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
const interp = (s, fn) => lit(s).replace(/\{\{([^}]+)\}\}/g, (_, x) => '${' + fn + '(' + expr(x) + ')}');

const actives = new Map(); // css -> class name
let js = '', ifN = 0;
const ifStack = [];
let depth = 0;
const re = /<\/?([a-zA-Z][\w-]*)((?:\s+[^\s=>]+(?:="[^"]*")?)*)\s*\/?>|([^<]+)/g;
let m;
while ((m = re.exec(body))) {
  const [tok, tag, attrs, text] = m;
  if (text !== undefined) { if (/^\s*$/.test(text) && text.includes('\n')) continue; js += interp(text.replace(/\s*\n\s*/g, ' '), 'e'); continue; }
  const close = tok.startsWith('</');
  const A = {}; (attrs || '').replace(/([^\s=]+)(?:="([^"]*)")?/g, (_, k, v) => (A[k] = v ?? ''));
  const bind = v => (v.match(/^\{\{([^}]+)\}\}$/) || [])[1];
  if (tag === 'sc-if') {
    if (close) { js += '` : \'\'}'; ifStack.pop(); }
    else { js += '${(' + expr(bind(A.value)) + ') ? `'; ifStack.push({ depth, key: 'i' + ifN++, n: 0 }); }
    continue;
  }
  if (tag === 'sc-for') {
    if (close) { js += '`).join(\'\')}'; scope.pop(); }
    else { js += '${(' + expr(bind(A.list)) + ' || []).map(' + A.as + ' => `'; scope.push(A.as); }
    continue;
  }
  if (close) { depth--; js += '</' + tag + '>'; continue; }
  let s = '<' + tag;
  const top = ifStack[ifStack.length - 1];
  if (top && top.depth === depth) s += ' data-k="' + top.key + String.fromCharCode(97 + top.n++) + '"';
  if (A.onPointerUp && !A.onPointerCancel) A.onPointerCancel = A.onPointerUp; // a cancelled touch must release too
  for (const [k, v] of Object.entries(A)) {
    if (k.startsWith('hint-') || k === 'data-screen-label') continue;
    if (k === 'style-active') {
      if (!actives.has(v)) actives.set(v, 'sa' + actives.size);
      s += ' class="' + actives.get(v) + '"';
      continue;
    }
    const on = k.match(/^on([A-Z]\w+)$/);
    if (on) { s += ' data-on-' + (EVT[on[1]] || on[1].toLowerCase()) + '="${on(' + expr(bind(v)) + ')}"'; continue; }
    if (k === 'ref') { s += ' data-keep data-ref="${on(' + expr(bind(v)) + ')}"'; continue; }
    s += ' ' + k + '="' + interp(v, 'q') + '"';
  }
  s += '>';
  js += s;
  if (!VOID.has(tag)) depth++;
}
const css = [...actives].map(([rule, cls]) => '.' + cls + ':active{' + rule.replace(/;?\s*$/, '') + '!important}').join('');

fs.writeFileSync(out, `// GENERATED by tools/dc-to-view.mjs from the Claude Design file. Edit the design and regenerate, or edit this by hand, not both.
// view(v, on): v = the values from App.renderVals() (plus refs), on(fn) registers a handler and returns its id.
const e = x => String(x ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const q = x => e(x).replace(/"/g, '&quot;');
export const css = ${JSON.stringify(css)};
export function view(v, on) {
  return \`${js}\`;
}
`);
console.log('wrote', out, (js.length / 1024).toFixed(1) + ' KB,', ifN, 'if-blocks,', actives.size, 'active styles');
